Fix so nose doesn't run test methods that it shouldn't.
Quoting the nose docs:
> As with py.test, nose tests need not be subclasses of
> unittest.TestCase.  Any function or class that matches the configured
> testMatch regular expression ((?:^|[\\b_\\.-])[Tt]est by default [...]
> and lives in a module that also matches that expression will be run as
> a test.

Before:

    ======================================================================
    ERROR: pgp.cipher.tests.test_twofish.make_block_tests
    ----------------------------------------------------------------------
    TypeError: make_block_tests() missing 3 required positional arguments:
      'module', 'module_name', and 'test_data'

After:

    all is well